// Mock Players
const players = [
    // Baltimore Ravens Players
    { name: 'Lamar Jackson', number: 8, position: 'QB', age: 26, experience: 5, weight: 193, height: 212, teamId: 1 },
    { name: 'Marlon Humphrey', number: 44, position: 'DB', age: 27, experience: 6, weight: 197, height: 197, teamId: 1 },
    { name: 'Calais Campbell', number: 93, position: 'DL', age: 37, experience: 15, weight: 290, height: 120, teamId: 1 },
    { name: 'Mark Andrews', number: 89, position: 'TE', age: 28, experience: 5, weight: 256, height: 112, teamId: 1 },
    { name: 'Rashod Bateman', number: 7, position: 'WR', age: 24, experience: 2, weight: 190, height: 92, teamId: 1 },
    { name: 'Patrick Queen', number: 6, position: 'LB', age: 23, experience: 3, weight: 229, height: 232, teamId: 1 },
    { name: 'Justin Tucker', number: 9, position: 'ST', age: 34, experience: 13, weight: 180, height: 185, teamId: 1 },
    { name: 'J.K. Dobbins', number: 27, position: 'RB', age: 24, experience: 3, weight: 209, height: 213, teamId: 1 },
    { name: 'Odell Beckham Jr.', number: 3, position: 'WR', age: 31, experience: 9, weight: 198, height: 201, teamId: 1 },
    { name: 'Roquan Smith', number: 18, position: 'LB', age: 26, experience: 5, weight: 232, height: 225, teamId: 1 },
    { name: 'Gus Edwards', number: 35, position: 'RB', age: 28, experience: 5, weight: 240, height: 234, teamId: 1 },
    { name: 'Tyus Bowser', number: 54, position: 'LB', age: 27, experience: 5, weight: 250, height: 245, teamId: 1 },
    { name: 'Chuck Clark', number: 36, position: 'DB', age: 28, experience: 6, weight: 208, height: 200, teamId: 1 },
    { name: 'Marcus Peters', number: 24, position: 'DB', age: 30, experience: 8, weight: 195, height: 202, teamId: 1 },
    { name: 'Cameron Heyward', number: 97, position: 'DL', age: 33, experience: 12, weight: 300, height: 310, teamId: 1 },
    { name: 'James Proche', number: 3, position: 'WR', age: 25, experience: 2, weight: 185, height: 180, teamId: 1 },
    { name: 'Ben Cleveland', number: 66, position: 'OL', age: 25, experience: 2, weight: 357, height: 335, teamId: 1 },
    { name: 'Josh Oliver', number: 89, position: 'TE', age: 26, experience: 4, weight: 250, height: 258, teamId: 1 },
    { name: 'Tavon Young', number: 25, position: 'DB', age: 28, experience: 6, weight: 174, height: 180, teamId: 1 },
    { name: 'Tyler Huntley', number: 2, position: 'QB', age: 24, experience: 2, weight: 219, height: 213, teamId: 1 },
    { name: 'Jihad Ward', number: 55, position: 'LB', age: 29, experience: 7, weight: 252, height: 240, teamId: 1 },
    { name: 'Daryl Worley', number: 24, position: 'DB', age: 29, experience: 6, weight: 205, height: 198, teamId: 1 },
    { name: 'DeShon Elliott', number: 26, position: 'DB', age: 26, experience: 4, weight: 210, height: 215, teamId: 1 },
    { name: 'Rochell Armstead', number: 22, position: 'RB', age: 24, experience: 3, weight: 230, height: 220, teamId: 1 },
    { name: 'Brandon Williams', number: 98, position: 'DL', age: 31, experience: 9, weight: 340, height: 330, teamId: 1 },
  
    // Kansas City Chiefs Players
    { name: 'Patrick Mahomes', number: 15, position: 'QB', age: 28, experience: 6, weight: 225, height: 129, teamId: 2 },
    { name: 'Travis Kelce', number: 87, position: 'TE', age: 34, experience: 11, weight: 250, height: 110, teamId: 2 },
    { name: 'Chris Jones', number: 95, position: 'DL', age: 29, experience: 7, weight: 310, height: 123, teamId: 2 },
    { name: 'Tyreek Hill', number: 10, position: 'WR', age: 29, experience: 7, weight: 185, height: 170, teamId: 2 },
    { name: 'Clyde Edwards-Helaire', number: 25, position: 'RB', age: 24, experience: 3, weight: 207, height: 209, teamId: 2 },
    { name: 'Tyrann Mathieu', number: 32, position: 'DB', age: 31, experience: 9, weight: 184, height: 184, teamId: 2 },
    { name: 'Frank Clark', number: 55, position: 'LB', age: 30, experience: 9, weight: 255, height: 243, teamId: 2 },
    { name: 'Jarran Reed', number: 90, position: 'DL', age: 30, experience: 8, weight: 305, height: 118, teamId: 2 },
    { name: 'Mecole Hardman', number: 17, position: 'WR', age: 26, experience: 4, weight: 187, height: 172, teamId: 2 },
    { name: 'Juan Thornhill', number: 22, position: 'DB', age: 27, experience: 5, weight: 205, height: 204, teamId: 2 },
    { name: 'Nick Bolton', number: 54, position: 'LB', age: 23, experience: 2, weight: 232, height: 229, teamId: 2 },
    { name: 'Orlando Brown Jr.', number: 57, position: 'OL', age: 27, experience: 5, weight: 340, height: 350, teamId: 2 },
    { name: 'Andrew Wylie', number: 77, position: 'OL', age: 28, experience: 6, weight: 310, height: 310, teamId: 2 },
    { name: 'Khalen Saunders', number: 99, position: 'DL', age: 28, experience: 5, weight: 324, height: 325, teamId: 2 },
    { name: 'Michael Burton', number: 40, position: 'RB', age: 31, experience: 9, weight: 240, height: 245, teamId: 2 },
    { name: 'Blake Bell', number: 81, position: 'TE', age: 33, experience: 8, weight: 250, height: 260, teamId: 2 },
    { name: 'Rashad Fenton', number: 27, position: 'DB', age: 26, experience: 4, weight: 190, height: 190, teamId: 2 },
    { name: 'Derrick Nnadi', number: 91, position: 'DL', age: 27, experience: 5, weight: 317, height: 315, teamId: 2 },
    { name: 'Deandre Baker', number: 30, position: 'DB', age: 26, experience: 5, weight: 193, height: 190, teamId: 2 },
    { name: 'Taco Charlton', number: 58, position: 'LB', age: 28, experience: 6, weight: 270, height: 250, teamId: 2 },
    { name: 'Joshua Kaindoh', number: 55, position: 'LB', age: 23, experience: 1, weight: 265, height: 250, teamId: 2 },
    { name: 'Amari Cooper', number: 19, position: 'WR', age: 29, experience: 8, weight: 210, height: 215, teamId: 2 },
    { name: 'Jody Fortson', number: 88, position: 'TE', age: 26, experience: 4, weight: 240, height: 225, teamId: 2 },
    { name: 'Dorian O’Daniel', number: 43, position: 'LB', age: 27, experience: 4, weight: 225, height: 230, teamId: 2 },
    { name: 'Darrynton Evans', number: 32, position: 'RB', age: 25, experience: 3, weight: 205, height: 195, teamId: 2 },
  
    // Philadelphia Eagles Players
    { name: 'Jalen Hurts', number: 1, position: 'QB', age: 25, experience: 3, weight: 223, height: 223, teamId: 3 },
    { name: 'A.J. Brown', number: 11, position: 'WR', age: 26, experience: 4, weight: 226, height: 226, teamId: 3 },
    { name: 'DeVonta Smith', number: 6, position: 'WR', age: 25, experience: 2, weight: 166, height: 170, teamId: 3 },
    { name: 'Fletcher Cox', number: 91, position: 'DL', age: 33, experience: 12, weight: 310, height: 128, teamId: 3 },
    { name: 'Darius Slay', number: 2, position: 'DB', age: 32, experience: 10, weight: 190, height: 200, teamId: 3 },
    { name: 'Jordan Mailata', number: 68, position: 'OL', age: 26, experience: 4, weight: 365, height: 158, teamId: 3 },
    { name: 'Lane Johnson', number: 65, position: 'OL', age: 33, experience: 10, weight: 317, height: 156, teamId: 3 },
    { name: 'Miles Sanders', number: 26, position: 'RB', age: 26, experience: 4, weight: 211, height: 214, teamId: 3 },
    { name: 'Jason Kelce', number: 62, position: 'OL', age: 35, experience: 13, weight: 310, height: 125, teamId: 3 },
    { name: 'Hassan Reddick', number: 7, position: 'LB', age: 29, experience: 6, weight: 240, height: 230, teamId: 3 },
    { name: 'Josh Sweat', number: 94, position: 'LB', age: 27, experience: 5, weight: 266, height: 260, teamId: 3 },
    { name: 'Brandon Graham', number: 55, position: 'LB', age: 35, experience: 12, weight: 265, height: 250, teamId: 3 },
    { name: 'Javon Hargrave', number: 97, position: 'DL', age: 30, experience: 8, weight: 310, height: 310, teamId: 3 },
    { name: 'Miles Sanders', number: 26, position: 'RB', age: 26, experience: 4, weight: 211, height: 214, teamId: 3 },
    { name: 'T.J. Edwards', number: 57, position: 'LB', age: 27, experience: 5, weight: 240, height: 245, teamId: 3 },
    { name: 'Davion Taylor', number: 52, position: 'LB', age: 24, experience: 3, weight: 230, height: 230, teamId: 3 },
    { name: 'Jaquiski Tartt', number: 28, position: 'DB', age: 31, experience: 9, weight: 210, height: 215, teamId: 3 },
    { name: 'Anthony Harris', number: 28, position: 'DB', age: 31, experience: 8, weight: 210, height: 215, teamId: 3 },
    { name: 'Kenneth Gainwell', number: 14, position: 'RB', age: 24, experience: 2, weight: 201, height: 201, teamId: 3 },
    { name: 'Jalen Reagor', number: 18, position: 'WR', age: 25, experience: 2, weight: 185, height: 190, teamId: 3 },
    { name: 'Quez Watkins', number: 16, position: 'WR', age: 26, experience: 3, weight: 196, height: 197, teamId: 3 },
    { name: 'Zech McPhearson', number: 27, position: 'DB', age: 24, experience: 3, weight: 196, height: 200, teamId: 3 },
    { name: 'Ndamukong Suh', number: 93, position: 'DL', age: 36, experience: 13, weight: 313, height: 335, teamId: 3 },
    { name: 'Linval Joseph', number: 75, position: 'DL', age: 35, experience: 12, weight: 330, height: 340, teamId: 3 },
    { name: 'Kyron Johnson', number: 58, position: 'LB', age: 25, experience: 1, weight: 235, height: 240, teamId: 3 },
  
    // Washington Commanders Players
    { name: 'Carson Wentz', number: 11, position: 'QB', age: 31, experience: 8, weight: 230, height: 222, teamId: 4 },
    { name: 'Terry McLaurin', number: 17, position: 'WR', age: 27, experience: 5, weight: 210, height: 210, teamId: 4 },
    { name: 'Antonio Gibson', number: 24, position: 'RB', age: 25, experience: 3, weight: 220, height: 215, teamId: 4 },
    { name: 'Jamin Davis', number: 52, position: 'LB', age: 25, experience: 3, weight: 234, height: 225, teamId: 4 },
    { name: 'Chase Young', number: 99, position: 'LB', age: 24, experience: 3, weight: 264, height: 255, teamId: 4 },
    { name: 'Jonathan Allen', number: 93, position: 'DL', age: 28, experience: 6, weight: 310, height: 315, teamId: 4 },
    { name: 'Daron Payne', number: 94, position: 'DL', age: 26, experience: 4, weight: 320, height: 320, teamId: 4 },
    { name: 'Kendall Fuller', number: 29, position: 'DB', age: 28, experience: 6, weight: 190, height: 195, teamId: 4 },
    { name: 'Logan Thomas', number: 82, position: 'TE', age: 32, experience: 9, weight: 250, height: 255, teamId: 4 },
    { name: 'William Jackson III', number: 23, position: 'DB', age: 31, experience: 7, weight: 197, height: 205, teamId: 4 },
    { name: 'J.D. McKissic', number: 41, position: 'RB', age: 29, experience: 7, weight: 204, height: 210, teamId: 4 },
    { name: 'Cole Holcomb', number: 55, position: 'LB', age: 27, experience: 5, weight: 240, height: 225, teamId: 4 },
    { name: 'Curtis Samuel', number: 10, position: 'WR', age: 27, experience: 5, weight: 195, height: 200, teamId: 4 },
    { name: 'Antonio Gibson', number: 24, position: 'RB', age: 25, experience: 3, weight: 220, height: 215, teamId: 4 },
    { name: 'Bobby McCain', number: 20, position: 'DB', age: 29, experience: 7, weight: 190, height: 198, teamId: 4 },
    { name: 'Dax Milne', number: 15, position: 'WR', age: 24, experience: 2, weight: 202, height: 190, teamId: 4 },
    { name: 'Khaleke Hudson', number: 47, position: 'LB', age: 25, experience: 3, weight: 220, height: 225, teamId: 4 },
    { name: 'Charles Leno Jr.', number: 72, position: 'OL', age: 31, experience: 8, weight: 320, height: 320, teamId: 4 },
    { name: 'Sam Cosmi', number: 76, position: 'OL', age: 24, experience: 3, weight: 314, height: 314, teamId: 4 },
    { name: 'Troy Apke', number: 29, position: 'DB', age: 29, experience: 6, weight: 211, height: 205, teamId: 4 },
    { name: 'Cam Sims', number: 89, position: 'WR', age: 28, experience: 6, weight: 219, height: 210, teamId: 4 },
    { name: 'David Mayo', number: 55, position: 'LB', age: 30, experience: 7, weight: 235, height: 230, teamId: 4 },
    { name: 'Benjamin St-Juste', number: 25, position: 'DB', age: 24, experience: 2, weight: 202, height: 200, teamId: 4 },
    { name: 'Sadiq Charles', number: 77, position: 'OL', age: 25, experience: 4, weight: 320, height: 310, teamId: 4 },
    { name: 'Mason Brooks', number: 73, position: 'OL', age: 24, experience: 2, weight: 305, height: 295, teamId: 4 },
  
    // San Francisco 49ers Players
    { name: 'Jimmy Garoppolo', number: 10, position: 'QB', age: 33, experience: 10, weight: 225, height: 225, teamId: 5 },
    { name: 'Deebo Samuel', number: 19, position: 'WR', age: 27, experience: 5, weight: 224, height: 215, teamId: 5 },
    { name: 'George Kittle', number: 85, position: 'TE', age: 30, experience: 6, weight: 250, height: 250, teamId: 5 },
    { name: 'Nick Bosa', number: 97, position: 'LB', age: 26, experience: 5, weight: 266, height: 270, teamId: 5 },
    { name: 'Fred Warner', number: 54, position: 'LB', age: 27, experience: 5, weight: 230, height: 230, teamId: 5 },
    { name: 'Trent Williams', number: 71, position: 'OL', age: 35, experience: 13, weight: 320, height: 318, teamId: 5 },
    { name: 'Jimmie Ward', number: 1, position: 'DB', age: 32, experience: 9, weight: 200, height: 205, teamId: 5 },
    { name: 'Trey Lance', number: 5, position: 'QB', age: 24, experience: 3, weight: 224, height: 224, teamId: 5 },
    { name: 'Brandon Aiyuk', number: 11, position: 'WR', age: 25, experience: 3, weight: 200, height: 200, teamId: 5 },
    { name: 'Arik Armstead', number: 91, position: 'DL', age: 30, experience: 8, weight: 292, height: 293, teamId: 5 },
    { name: 'Raheem Mostert', number: 31, position: 'RB', age: 31, experience: 8, weight: 186, height: 192, teamId: 5 },
    { name: 'Elijah Mitchell', number: 25, position: 'RB', age: 25, experience: 3, weight: 200, height: 202, teamId: 5 },
    { name: 'Kyle Juszczyk', number: 44, position: 'RB', age: 33, experience: 10, weight: 240, height: 240, teamId: 5 },
    { name: 'Mike McGlinchey', number: 69, position: 'OL', age: 28, experience: 6, weight: 310, height: 315, teamId: 5 },
    { name: 'Jordan Willis', number: 75, position: 'LB', age: 28, experience: 6, weight: 270, height: 260, teamId: 5 },
    { name: 'Jimmy Ward', number: 1, position: 'DB', age: 32, experience: 9, weight: 200, height: 205, teamId: 5 },
    { name: 'K’Waun Williams', number: 24, position: 'DB', age: 32, experience: 9, weight: 190, height: 190, teamId: 5 },
    { name: 'Tashaun Gipson', number: 39, position: 'DB', age: 33, experience: 11, weight: 212, height: 210, teamId: 5 },
    { name: 'Ambry Thomas', number: 20, position: 'DB', age: 24, experience: 2, weight: 195, height: 200, teamId: 5 },
    { name: 'Jason Verrett', number: 22, position: 'DB', age: 31, experience: 9, weight: 190, height: 195, teamId: 5 },
    { name: 'Dre Greenlaw', number: 57, position: 'LB', age: 26, experience: 5, weight: 230, height: 225, teamId: 5 },
    { name: 'Tyler Kroft', number: 81, position: 'TE', age: 32, experience: 9, weight: 250, height: 260, teamId: 5 },
    { name: 'Kerry Hyder Jr.', number: 92, position: 'LB', age: 32, experience: 9, weight: 275, height: 270, teamId: 5 },
    { name: 'Jauan Jennings', number: 15, position: 'WR', age: 26, experience: 4, weight: 212, height: 210, teamId: 5 },
    { name: 'Charlie Woerner', number: 89, position: 'TE', age: 26, experience: 4, weight: 250, height: 240, teamId: 5 },
]


// Mock Team
let team1, team2, team3, team4, team5;
const teams = [
    { teamName: 'Baltimore Ravens' },
    { teamName: 'Kansas City Chiefs' },
    { teamName: 'Philadelphia Eagles' },
    { teamName: 'Washington Commanders' },
    { teamName: 'San Francisco 49ers' },
]

// Mock Account
const accounts = [
    { username: 'user1', password: 'password123', teamId: 1, role: 'user' },
    { username: 'user2', password: 'password123', teamId: 2, role: 'user' },
    { username: 'user3', password: 'password123', teamId: 3, role: 'user' },
    { username: 'user4', password: 'password123', teamId: 4, role: 'user' },
    { username: 'user5', password: 'password123', teamId: 5, role: 'user' },
    { username: 'admin1', password: 'adminpass', teamId: 1, role: 'admin' }, 
]

// Store in-memory repositories
const MockData = {
  accounts,
  teams,
  players,
};

module.exports = { MockData };